### ISSUE TITLE
MPUMALANGA 

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#5] opened 2020-09-17 20:24 UTC
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/Mpumalanga%20COVID%2019%20Expenditure%20Report.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by tristynferreiro** [comment] 2020-10-03 08:17
@jbothma can I have this one?

**Comment by jbothma** [comment] 2020-10-03 08:26
go for it! Thanks!

**Comment by tristynferreiro** [comment] 2020-10-03 08:37
<img width="805" alt="Screenshot 2020-10-03 at 10 36 12" src="https://user-images.githubusercontent.com/65689669/94987149-5112ff00-0564-11eb-9e09-7076da37aa73.png">
Should I capture this information?

**Comment by tristynferreiro** [comment] 2020-10-03 09:11
@jbothma when using tabula it made one joint table. Should I leave it in this state or separate the tables so that they mirror the PDF?

**Comment by tristynferreiro** [comment] 2020-12-08 20:14
This is a duplicate of Issue 4, I have closed all these PR's

**Closed as completed by tristynferreiro** 2020-12-08 20:14 UTC
