### ISSUE TITLE
FREE STATE Provincial Treasury pass 1

### ISSUE THREAD

**Issue by jbothma** [keep-the-receipts/data-extraction#15] opened 2020-09-17 20:26 UTC
- [Source URL](http://ocpo.treasury.gov.za/COVID19/Documents/FREE%20STATE%20FINANCE%20TENDER%20BULLETIN%20-%201.pdf)
- [Trusted Archive copy]() (Fill this using the archive URL generated by e.g. https://archive.org/web/ Save Page Now)

**Comment by enemkaywun** [comment] 2020-10-03 12:08
please assign this one to me?

**Comment by jbothma** [comment] 2020-10-15 20:17
This is now on https://keepthereceipts.org.za/?implementation_location_province=Free+State

**Comment by tristynferreiro** [comment] 2020-10-30 10:10
We are not uploading this file since it is a duplicate of a file that has already been uploaded https://github.com/keep-the-receipts/data-extraction/blob/master/Provincial%20Government/Free%20State/Provincial%20Treasury/FREE%20STATE%20FINANCE%20TENDER%20BULLETIN%20-%201%20–%20pass%201.csv issue #16

**Closed as completed** 2020-10-30 10:46 UTC
